name: gba
dependencies:
  args: ^1.0.0
  binary: ^0.1.3
  cli_repl: ^0.1.3
  logging: ^0.11.3
dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.2.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0